apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eventmanagement
  name: eventmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventmanagement
  template:
    metadata:
      labels:
        app: eventmanagement
    spec:
      containers:
      - image: ${ECR_REPOSITORY}:${IMAGE_TAG}
        imagePullPolicy: "Always"
        name: event-management-service
        envFrom:
        - configMapRef:
            name: event-service-config
        ports:
        - containerPort: 3000        
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: eventmanagement
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: eventmanagement
